[tool.poetry]
name = "electricitymap-contrib"
version = "1.0.0"
description = ""
license = "AGPL-3.0-or-later"
authors = ["Electricity Maps <app@electricitymaps.com>"]
packages = [
    { include = "electricitymap" }
]
include = ["config/*.json"]

[tool.poetry.dependencies]
python = '>= 3.8, < 4.0'
pydantic = "^1.9.0"

arrow = {version="0.16.0", optional=true}
beautifulsoup4 = {version="~4.6.0", optional=true}
demjson3 = {version="^3.0.5", optional=true}
freezegun = {version="^0.3.15", optional=true}
html5lib = {version = "^1.1", optional = true}
imageio = {version="^2.18.0", optional=true}
lxml = {version="^4.9.1", optional=true}
mock = {version="^2.0.0", optional=true}
opencv-python = {version="4.6.0.66", optional=true}
pandas = {version="^1.4.4", optional=true}
Pillow = {version="^9.1.1", optional=true}
pytesseract = {version="0.2.0", optional=true}
ree = {version = "2.3.2", optional = true}
requests = {version="~2.25.1", optional=true}
signalr-client-threads = {version="~0.0.12", optional=true}
tqdm = {version="^4.64.0", optional=true}
xlrd = {version="^2.0.1", optional=true}
xmltodict = {version = "^0.13.0", optional=true}
black = "22.12.0"
isort = "5.12.0"
deepdiff = "^5.8.1"
PyYAML = "^6.0"
openpyxl = {version="^3.1.2", optional=true}
pydataxm = {version="^0.3.2", optional=true}
odfpy = {version="^1.4.1", optional=true}
ruamel-yaml = "^0.17.24"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.2"
mock = "^2.0.0"
pylint = "^2.13.7"
pylint-pydantic = "^0.1.8"
requests-mock = "~1.3.0"
testfixtures = "^7.0.0"
click = "<=8.0"
pytest = "^7.1.2"

[tool.poetry.scripts]
test-parser = 'test_parser:test_parser'
test_parser = 'test_parser:test_parser'
check = 'scripts.tooling:check'
format = 'scripts.tooling:format'
lint = 'scripts.tooling:lint'
test = 'scripts.tooling:test'



[tool.poetry.extras]
parsers = [
    "arrow",
    "beautifulsoup4",
    "demjson3",
    "eiapy",
    "html5lib",
    "imageio",
    "lxml",
    "mock",
    "pandas",
    "Pillow",
    "pytesseract",
    "ree",
    "requests",
    "opencv-python",
    "xlrd",
    "freezegun",
    "signalr-client-threads",
    "tqdm",
    "openpyxl",
    "pydataxm",
    "odfpy"]


validators = [
    "arrow",
    "pandas"
]

scripts = [
    "xmltodict"
]

[tool.isort]
profile = "black"

[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"

[tool.pylint.MASTER]
load-plugins = "pylint_pydantic"

[tool.pytest.ini_options]
testpaths = [
    "tests",
    "parsers/test",
    "electricitymap/contrib/lib/tests",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
