bounding_box:
  - - 130.66
    - 33.585
  - - 134.54
    - 35.74
capacity:
  geothermal: 0
  oil: 850
  coal: 3850
  gas: 4000
  hydro: 780
  hydro storage: 2123
  nuclear: 0
  solar: 5690
  wind: 365
  biomass: 500
emissionFactors:
  lifecycle:
    unknown:
      _comment: 'Source: Enerdata 2022 Japanese National Average'
      _url:
        - https://www.climate-transparency.org/wp-content/uploads/2022/10/CT2022-Japan-Web.pdf
      source: Enerdata 2022
      value: 462
contributors:
  - tmslaine
  - lorrieq
  - PPsyrius
parsers:
  consumptionForecast: JP.fetch_consumption_forecast
  price: JP.fetch_price
  production: JP.fetch_production
timezone: Asia/Tokyo
