bounding_box:
  - - -188
    - 51
  - - -130
    - 72
emissionFactors:
  direct:
    coal:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 1054.589992
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 470.7986093
    oil:
      datetime: '2021-01-01'
      source: eGrid 2020
      value: 713.1828107
  lifecycle:
    coal:
      datetime: '2020-01-01'
      source: >-
        eGrid 2020; Oberschelp, Christopher, et al. "Global emission hotspots of
        coal power generation."
      value: 1061.619377
    gas:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 590.7986093
    oil:
      datetime: '2021-01-01'
      source: eGrid 2020; IPCC 2014
      value: 957.1828107
sources:
  IPCC 2014:
    link: >-
      https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: >-
      https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
timezone: America/Anchorage
